env:
  browser: true

extends: ["airbnb-base", "plugin:prettier/recommended"]

parser: babel-eslint

parserOptions:
  ecmaVersion: 6

# Global scoped method and vars
globals:
  __dirname: true
  require: true
  process: true
  ENV: true
  module: true
